# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: w4A7S9a1@
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://PlayBack.ru/
      name: PlayBack
    - url: https://sochiparkhotel.ru/
      name: sochiparkhotel






